### ISSUE TITLE
Upgrade to Neo4j Core 5.18.0

### ISSUE THREAD

**Issue by gumshoes** [DozerDB/dozerdb-plugin#11]
Upgrade to 5.18.0 which came out 2024-03-13.
I know this is very recent but the DozerDB upgrade to 5.17 (2024-02-23) was done within six days, amazing work.
[5.18.0](https://neo4j.com/release-notes/database/neo4j-5/)

thanks

**Comment by jmsuhy** [comment]
We actually just started this, in the future we can aim at getting our releases faster once a Neo4j core release is made.  I will update this ticket when the updates are completed and everything is built and pushed.

**Comment by gumshoes** [comment]
Crazy fast, thanks.
I am using `graphstack/dozerdb:5.17.0.0-alpha.1` and hope to use a 5.18 ver of that so that I can load a dump from that ver.

**Comment by jmsuhy** [comment]
FYI - We are updating to Neo4j Core 5.18.1 - they released a patch right after 5.18.0.

**Comment by jmsuhy** [comment]
5.18.1 version has been completed and published.  Turn around times will be faster in the future.

**Comment by gumshoes** [comment]
Thanks, I just tested and loaded a dump from 5.18 AuraDB and it works fine so far.
