### ISSUE TITLE
Confusing installation instructions

### ISSUE THREAD

**Issue by curious-broccoli** [DozerDB/dozerdb-plugin#12]
not sure if this is the right repository:

In the installation instructions the environment variable creation

> and set the following path variable:
> export CLASSPATH_PREFIX=/Absolute/Path/To/$NEO4J_HOME/lib/dozerdb-plugin-x.x.x.x.jar

is a weird description because it makes no sense that there would need to be a path before the $NEO4J_HOME variable.

I think it would be less confusing if it said something like

> and set the CLASSPATH_PREFIX environment variable to the absolute path of the plugin:
> export CLASSPATH_PREFIX=$NEO4J_HOME/lib/dozerdb-plugin-x.x.x.x.jar

**Comment by jmsuhy** [comment]
Yes this is a good place for this ticket.

Good point.

We will update the instructions with your recommendation on the site. 

Thanks for pointing that out.   

Is there anything else that you think of?

**Comment by jmsuhy** [comment]
The content was uploaded and a windows set example was also added. 

See: https://dozerdb.org

**Comment by jmsuhy** [comment]
Let me know if you have any other recommendations. If you do find anything else, please reopen this ticket.

Thank you for finding that!
