### ISSUE TITLE
Commercial Use Case

### ISSUE THREAD

**Issue by harikrishna-ps** [DozerDB/dozerdb-plugin#13]
Would it be legal to use this for commercial purposes in a setup with multiple databases on Neo4j? @jmsuhy, could you provide clarification on this?

**Comment by jmsuhy** [comment]
Of course you can use this for commercial purposes.  It's 100% GPL - free and open source.

**Comment by harikrishna-ps** [comment]
Thanks, @jmsuhy. I have another question: Are there any licensing concerns with Neo4j when utilizing the enterprise features through DozerDB? I appreciate your help, and thank you in advance!

**Comment by jmsuhy** [comment]
From previous ticket.  There are no limitations on commercial usage. 

 Neo4j core is GPL licensed and DozerDB is GPL licensed.

The GPL is a free and open source license. There are no commercial or usage limitations whatsoever for GPL or AGPL.

You can reach out to the Free Software Foundation who owns the copyright to the GPL and AGPL licenses and ask specific questions about the GPL as well.

**Comment by harikrishna-ps** [comment]
Thanks, @jmsuhy
