### ISSUE TITLE
Licensing concerns with Neo4j

### ISSUE THREAD

**Issue by harikrishna-ps** [DozerDB/dozerdb-plugin#14]
Are there any licensing concerns with Neo4j when utilizing the enterprise features through DozerDB? I appreciate your help, and thank you in advance!

**Comment by jmsuhy** [comment]
Of course not.  Neo4j core is GPL licensed and DozerDB is GPL licensed.    

The GPL is a free and open source license. There are no commercial or usage limitations whatsoever for GPL or AGPL.

You can reach out to the Free Software Foundation who owns the copyright to the GPL and AGPL licenses and ask specific questions about the GPL as well.

**Comment by jmsuhy** [comment]
https://www.gnu.org/licenses/gpl-3.0.en.html

**Comment by harikrishna-ps** [comment]
Thanks, @jmsuhy
