### ISSUE TITLE
Please support Neo4j 5.20.0

### ISSUE THREAD

**Issue by breadbread1984** [DozerDB/dozerdb-plugin#16]
Please support Neo4j 5.20.0, thx

**Comment by jmsuhy** [comment]
Neo4j has not released any of the code for 5.20.0 in their official GitHub repository.   Please create a ticket in the official Neo4j repo asking them where the code is. 

As soon as the code is published, we will have a release.

Under the GPL license that community is released under - I think they are supposed to make the source code available.  I am checking on that soon.

**Comment by jmsuhy** [comment]
FYI - see ticket I created on Neo4j GitHub repo. I suggest that everyone makes the same request for the source code since they are not following the GPL V3 by not releasing it.   

https://github.com/neo4j/neo4j/issues/13464

**Comment by breadbread1984** [comment]
@jmsuhy thanks

**Comment by jmsuhy** [comment]
They released the code after I submitted the ticket.   We will have 5.20.0 out this week.

**Comment by jmsuhy** [comment]
Version supporting 5.20.0 of Neo4j Core complete and available as of today.  See: https://dozerdb.org
