### ISSUE TITLE
Please support Neo4j 5.21.3

### ISSUE THREAD

**Issue by gumshoes** [DozerDB/dozerdb-plugin#20]
It appears that Neo4j is now at 5.21.3 (or higher) and exports from it will not load into Dozerdb 5.21.2.

thanks

**Comment by jmsuhy** [comment]
Thanks for letting us know. It looks like Neo4j 5.22.0 is out so we will get an update out shortly. 

As for exports not loading to a lower version - that would be a Neo4j issue and you may want to file it in their repo. 

I am going to a separate ticket for updating to Neo4j 5.22.0 and will close this ticket once its done.

**Comment by jmsuhy** [comment]
FYI - there is not a 5.21.3 tag in the Neo4j github repo so we will jump to the latest tag available : 5.22.0

**Comment by jmsuhy** [comment]
I created a ticket for supporting 5.22.0 - which is the next tag in the Neo4j Github repository beyond 5.21.2
See:  https://github.com/DozerDB/dozerdb-plugin/issues/21

I am closing this specific ticket.
