### ISSUE TITLE
Neo4j 4.1

### ISSUE THREAD

**Issue by yliuhz** [DozerDB/dozerdb-plugin#24]
Hi DozerDB team,

Thanks for your amazing work! I am wondering is it possible to use dozerdb-plugin-4.4.25.0-alpha.1.jar on the older Neo4j 4 versions, such as Neo4j 4.1?

Best regards,
Yue

**Comment by jmsuhy** [comment]
I am not sure, you would have to try.   Essentially each version of dozer DB plug-in is compiled against the equivalent Neo4j core version.  

we have been focusing on 5.x releases mainly as that is where most of the current users are.

Neo4j uses semantic versioning, so 4.4 would have some changes that makes it incompatible with 4.1 - but those changes could have nothing to do with the interfaces the plug-in works with.

**Comment by jmsuhy** [comment]
It looks like the 4.4 version may not work with 4.1.
we are focusing on updating 5.x versions but I can show you how you can create a 4.1 version.

in fact creating a ‘How to build’ document is on our list of documentation updates.

**Comment by jmsuhy** [comment]
As our team grows, we can revisit building out 4.x versions of the plugin, but for now we are focusing on the newest 5.x.   If you are interested in helping,  we are writing a series of howto docs for new volunteers.
