### ISSUE TITLE
Fabric feature not supported 

### ISSUE THREAD

**Issue by ronysalem** [DozerDB/dozerdb-plugin#29]
Hello my i ask when will fabric feature will be supported

**Comment by jmsuhy** [comment]
We are planning on starting this in the next few months.   As the team of volunteers grows - we will be able to accelerate these feature releases. 

Neo4j Core already has bulk of the sub-systems to support fabric in place, so it is just a matter of connecting everything together. 

On another note - we are setting up a voting system to allow the community to vote on next feature set.

Once the voting system is setup - we will let everyone know.
