### ISSUE TITLE
Admin functions

### ISSUE THREAD

**Issue by ILABUTK** [DozerDB/dozerdb-plugin#33]
Hi, anyone was able to use the admin functions, such as creating a role etc? I cannot even run "SHOW ROLES".

It throws an error: 
`Neo.ClientError.Statement.UnsupportedAdministrationCommand`

My end goal is to create an admin-like user for a specific database. 

Here is how I run the docker:

```
sudo docker run -it -d --name neo4j \
      --restart always\
      --publish=7473:7473 \
      --publish=7687:7687 \
      --user="$(id -u):$(id -g)" \
      -v $HOME/conf:/var/lib/neo4j/conf \
      -v $HOME/certificates:/var/lib/neo4j/certificates \
      -v $HOME/data:/data \
      -v $HOME/import:/var/lib/neo4j/import \
      -v $HOME/plugins:/plugins \
      -v $HOME/logs:/logs \
      -e NEO4J_AUTH=neo4j/MYPWD \
      -e NEO4J_apoc_export_file_enabled=true \
      -e NEO4J_apoc_import_file_enabled=true \
      -e NEO4J_apoc_import_file_use__neo4j__config=true \
      -e NEO4J_PLUGINS='["apoc"]' \
      -e NEO4J_dbms_security_procedures_unrestricted='*' \
      graphstack/dozerdb:5.22.0.0-alpha.1
```

**Comment by jmsuhy** [comment]
This is an upcoming feature - we are going to implement the enterprise user management features, as well as being able to plugin to oidc, etc.

**Comment by ILABUTK** [comment]
Great! Thanks!

**Comment by f1-outsourcing** [comment]
Should this be in 5.26.3? Because `show roles;` gives Neo.ClientError.Statement.UnsupportedAdministrationCommand

**Comment by jmsuhy** [comment]
We haven't implemented that feature yet - but it is on our high priority list internally.  We will sync everything with a roadmap document that we are going to create and maintain.

Essentially, as we implement specific features, then we will also turn them on so they can be used via browser.  

Security is our next big piece we are focusing on.
