### ISSUE TITLE
Clustering support

### ISSUE THREAD

**Issue by ghost** [DozerDB/dozerdb-plugin#34]
Hello, this seems like an awesome project, I played around with it for a while but I wasn't able to get clustering to work in Kubernetes, is this something that is currently unsupported?

Thanks

**Comment by jmsuhy** [comment]
We are not planning on adding clustering to the plugin right now.  Neo4j’s clustering is essentially high availability. It lacks the true sharding capabilities found in platforms like Elasticsearch or TigerGraph.

If your use case involves an ingest pipeline that distributes data across multiple systems—such as a graph database, search engine, and vector database—alternative open source or cloud based high availability solutions may be more effective than Neo4j’s clustering. 

The best approach depends on your specific needs.

If you have a ton of writes flowing in,   For example, you can leverage Kafka and feed the graph and elastic search at the same time.

We need to write some blog posts showing the different approaches that can be used.
