### ISSUE TITLE
Can not drop database

### ISSUE THREAD

**Issue by PeiHaigang** [DozerDB/dozerdb-plugin#37]
Hello John,
Thank you for developing the plugin. I successfully loaded the plugin under version 4.4 and created multiple databases. However, I encountered an error when attempting to delete a database. The error message is:
`Unsupported administration command: DROP DATABASE xxx DESTROY  DATA`
How can I resolve this issue?
Thanks！

**Comment by jmsuhy** [comment]
We are focusing on the 5.x version moving forward - and have been focused on that.   However if someone in the community wants to back port the many updates made in DozerDB 5.x versions - we can give guidance.  

You can drop databases in current 5.x dozerdb version.
